#[derive(Debug, PartialEq)]
pub enum Token {
    // Bindings and Keywords
    Identifier(String),
    Comment(String),

    // Literals
    String(String),
    Int(String),
    Float(String),
    Char(char),
    Bool(bool),

    // Operators
    Bang,
    Tilde,
    Percent,
    Colon,
    Period,
    Ampersand,
    Plus,
    Minus,
    Asterisk,
    ForwardSlash,
    BackwardSlash,
    Equal,
    LessThan,
    LessThanOrEqual,
    GreaterThan,
    GreaterThanOrEqual,
    PlusPlus,
    Caret,
    VerticalBar,
    NotEqual,
    LeftParen,
    Unit,
    RightParen,
    RightArrow,
    LeftArrow,
    PeriodPeriod,
    ColonColon,
    EqualEqual,
    Comma,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    QuestionMark,
    SemiColon,
    SemiColonSemiColon,
    Illegal,
    EOF,
}
